### ISSUE TITLE
Build script

### ISSUE THREAD

**Issue by marcelklehr** [kingsman142/playlist-generator#1]
Hey!

I saw you intend to add a build script. It might be worth taking inspiration from the build script I wrote for floccus: https://github.com/marcelklehr/floccus/blob/develop/gulpfile.js

**Comment by kingsman142** [comment]
Oh yeah, this looks great. I think that'd be somewhat easy to transform for our uses. I'll look into it this week, unless you want to assign it to yourself.

**Comment by kingsman142** [comment]
Note for future reference: I don't like that npm adds additional files to the directory when installing new packages (e.g. glub-zip), and Python is pretty similar stylistically to Javascript (i.e. they're both typeless and verbose). Plus, I've recently been writing a lot of Python, and I'm pretty much going to be the only person running the build script, so it just made sense to write it all in Python.

To run the script, just run `python3 build.py` and it will create a zip file automatically. Requires installation of the `glob`, `json`, and `zipfile` libraries (e.g. `pip3 install zipfile`) if they are not already installed in your distribution of Python (if I recall correctly, they should all be automatically supplied).
